FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy seluruh kode (akan dioverride oleh volumes di docker-compose untuk hot-reload)
COPY . .

EXPOSE 5173

# Jalankan Vite dan ekspos ke network Docker
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]