FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
# Gunakan nodemon untuk hot-reload backend
RUN npm install -g nodemon
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 5000

# Jalankan server menggunakan nodemon
CMD ["nodemon", "server.js"]